services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: jd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app_container
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/jd
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    restart: unless-stopped
    ports:
      - "9090:8080"   # Jenkins UI http://localhost:9090
      - "50000:50000" # Port Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins control Docker
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"  # Optional, if want to access from /jenkins

volumes:
  mariadb_data:
  jenkins_home: